
name: Build iOS with Flet

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Flet
        run: |
          python -m pip install --upgrade pip
          python -m pip install flet==1.0.4

      - name: Compilar aplicación iOS
        run: flet build ipa --yes --no-rich-output

      - name: Guardar resultado
        uses: actions/upload-artifact@v4
        with:
          name: flet-ipa
          path: build/ipa/**
          if-no-files-found: error
