
name: Build iOS with Flet

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Compilar aplicación iOS
        uses: flet-dev/flet-build-action@v1
        with:
          target: ipa
          project-dir: .
